# -*- coding: utf-8 -*-
"""Linear model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHY-1u_DNWsqOSMF449C6IeFiuePJerN
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Sample dataset
data = {
    'Hours': [1, 2, 3, 4, 5],
    'Marks': [20, 40, 50, 60, 80]
}

# Create DataFrame
df = pd.DataFrame(data)

# Input and Output
X = df[['Hours']]
y = df['Marks']

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1)

# Create Linear Regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Predict values
pred = model.predict(X_test)

# Calculate Mean Squared Error
mse = mean_squared_error(y_test, pred)

# Output
print("Predicted Marks:", pred)
print("Mean Squared Error:", mse)

# Visualization
plt.scatter(X, y, color='blue', label='Actual Data')
plt.plot(X_test, pred, color='red',
         linewidth=2, label='Predicted Line')

# Labels and title
plt.xlabel("Hours")
plt.ylabel("Marks")
plt.title("Linear Regression Model")

# Legend
plt.legend()

# Show graph
plt.show()

